### ISSUE TITLE
1.19.2fabric bug，导出路径错误导致没有lang文件

### ISSUE THREAD

**Issue by Doushabao233** [LocalizedMC/FTBQLocalizationKeys-Arch#2]
急急急！正准备给整合包做汉化，结果这个mod出bug掉链子了

想要复现这个问题贼简单，在模组1.19.2fabric版本中导出本地化键，后台报错

```
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: java.io.IOException: Cannot create directory '**USERSDIR**\instances\CavesCliffsPlus\ftbqlocalizationkeys\**USERSDIR**\instances\CavesCliffsPlus\kubejs\assets\kubejs\lang'.
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at org.apache.commons.io.FileUtils.mkdirs(FileUtils.java:2200)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at org.apache.commons.io.FileUtils.createParentDirectories(FileUtils.java:1113)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2449)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3540)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at org.apache.commons.io.FileUtils.write(FileUtils.java:3222)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at org.apache.commons.io.FileUtils.write(FileUtils.java:3206)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at org.localmc.tools.ftbqkeys.FTBQKeysMod.saveLang(FTBQKeysMod.java:27)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at org.localmc.tools.ftbqkeys.command.FTBQKeysCommand.lambda$serverRegisterCommandsEvent$2(FTBQKeysCommand.java:177)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_2170.redirect$zlb000$architectury$performCommand(class_2170.java:545)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_2170.method_9249(class_2170.java:271)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_3244.method_45010(class_3244.java:1339)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_3244.method_44356(class_3244.java:1320)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_1255.method_5386(class_1255.java:68)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:157)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:131)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_1255.method_18857(class_1255.java:140)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.server.MinecraftServer.handler$bfh000$carpet$modifiedRunLoop(MinecraftServer.java:4394)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[17/08/2023 12:42:17 下午] [Server thread/INFO] [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

很显然这个模组在创建lang文件的时候本来应该把他放在`**USERSDIR**\instances\CavesCliffsPlus\ftbqlocalizationkeys\lang`或者`**USERSDIR**\instances\CavesCliffsPlus\kubejs\assets\kubejs\lang`的，但是路径拼接错了，导致直接没有lang文件

我又在单独的实例里试了一下

![image](https://github.com/LocalizedMC/FTBQLocalizationKeys-Arch/assets/64591791/826b9448-933b-4471-89f8-5f9bdd5435ab)

不是应该三个文件夹吗backup、config和lang？为什么只有一个，这个是我在一个只含有本模组的示例中测试的，如果在我的整合包中使用这个模组，也只有两个文件夹，就是没有lang文件夹。

**Comment by TexBlock** [comment]
FTBQLocalKeys 理论上会将lang直接放在kubejs的文件夹里面

**Comment by Doushabao233** [comment]
> FTBQLocalKeys 理论上会将lang直接放在kubejs的文件夹里面

emm，我试试

**Comment by Doushabao233** [comment]
> FTBQLocalKeys 理论上会将lang直接放在kubejs的文件夹里面

因为日志里直接报错了，所以我猜他根本没生成zh_cn.json

```
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: java.io.IOException: Cannot create directory '**USERSDIR**\instances\CavesCliffsPlus\ftbqlocalizationkeys\**USERSDIR**\instances\CavesCliffsPlus\kubejs\assets\kubejs\lang'.
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at org.apache.commons.io.FileUtils.mkdirs(FileUtils.java:2200)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at org.apache.commons.io.FileUtils.createParentDirectories(FileUtils.java:1113)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:2449)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3540)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at org.apache.commons.io.FileUtils.write(FileUtils.java:3222)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at org.apache.commons.io.FileUtils.write(FileUtils.java:3206)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at org.localmc.tools.ftbqkeys.FTBQKeysMod.saveLang(FTBQKeysMod.java:27)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at org.localmc.tools.ftbqkeys.command.FTBQKeysCommand.lambda$serverRegisterCommandsEvent$2(FTBQKeysCommand.java:177)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_2170.redirect$zlb000$architectury$performCommand(class_2170.java:545)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_2170.method_9249(class_2170.java:271)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_3244.method_45010(class_3244.java:1339)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_3244.method_44356(class_3244.java:1320)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_1255.method_5386(class_1255.java:68)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:157)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:131)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.class_1255.method_18857(class_1255.java:140)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.server.MinecraftServer.handler$bfh000$carpet$modifiedRunLoop(MinecraftServer.java:4394)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[18/08/2023 08:19:59 上午] [Server thread/INFO] [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

![image](https://github.com/LocalizedMC/FTBQLocalizationKeys-Arch/assets/64591791/05ccc440-a152-497d-9684-0552e5201ac8)

如你所见，这个文件夹里根本没有东西（它还是我自己建立的）

**Comment by Doushabao233** [comment]
所以，这个问题能解决吗？

有大概一周了

**Comment by Doushabao233** [comment]
额

**Comment by Doushabao233** [comment]
![image](https://github.com/LocalizedMC/FTBQLocalizationKeys-Arch/assets/64591791/74aa2cae-450b-4fcd-8593-48fbacac0ad5)

没有……

**Comment by TexBlock** [comment]
你试试这个有问题吗
https://github.com/LocalizedMC/FTBQLocalizationKeys-Arch/actions/runs/5971026017

**Comment by TexBlock** [comment]
FIX IN 1.1.0

**Comment by Doushabao233** [comment]
> FIX IN 1.1.0

你做得好啊！！！！
