### ISSUE TITLE
1.20 fabric doesn't work.

### ISSUE THREAD

**Issue by m0nstrum** [LocalizedMC/FTBQLocalizationKeys-Arch#4]
When i type command, nothing happens.
Logs after typing look like this
[02:25:36] [Server thread/INFO]: [STDERR]: java.lang.RuntimeException: Mixin transformation of org.localmc.tools.ftbqkeys.mixin.ChapterImageMixin failed
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at org.localmc.tools.ftbqkeys.FTBQKeysMod.lambda$init$2(FTBQKeysMod.java:114)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2170.redirect$bca000$architectury$performCommand(class_2170.java:1545)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_2170.method_9249(class_2170.java:287)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_45010(class_3244.java:1341)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3244.method_44356(class_3244.java:1321)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_5386(class_1255.java:67)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_3738.run(class_3738.java:18)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:156)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:130)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18857(class_1255.java:139)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Unknown Source)
[02:25:36] [Server thread/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for org.localmc.tools.ftbqkeys.mixin.ChapterImageMixin. Mixin is defined in ftbqkeys.common.mixins.json and cannot be referenced directly
[02:25:36] [Server thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:334)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
[02:25:36] [Server thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
[02:25:36] [Server thread/INFO]: [STDERR]: 	... 25 more

**Comment by Yizhouuu** [comment]
same issue with 1.20.1 fabric Prominence RPG modpack

**Comment by xXStrayXx** [comment]
same issue with 1.20.1 forge modpack
